INSERT INTO USER (FirstName, LastName, Addrese, FavoritePayment) 
VALUES 
('Jean', 'Dupont', '123 Rue de Paris', 'Carte'),
('Sophie', 'Martin', '456 Rue des Lilas', 'Paypal'),
('Paul', 'Leclerc', '789 Avenue de France', 'Virement'),
('Marie', 'Durand', '25 Boulevard des Champs', 'Carte'),
('Luc', 'Bernard', '10 Rue des Fleurs', 'Paypal'),
('Pierre', 'Moreau', '5 Rue de Lyon', 'Virement'),
('Julie', 'Lambert', '36 Rue Saint Honore', 'Carte'),
('Antoine', 'Blanc', '12 Rue des Ecoles', 'Paypal'),
('Claire', 'Garcia', '18 Rue de Bretagne', 'Virement'),
('Alex', 'Girard', '7 Avenue Montaigne', 'Carte'),
('Camille', 'Rodriguez', '54 Rue Montmartre', 'Paypal'),
('Louis', 'Perrin', '22 Rue du Temple', 'Carte'),
('Emma', 'Lopez', '98 Boulevard Raspail', 'Virement'),
('Hugo', 'Fournier', '76 Rue de la Republique', 'Carte'),
('Laura', 'Dupuis', '11 Rue du Faubourg', 'Paypal'),
('Thomas', 'Gonzalez', '33 Rue de Rivoli', 'Carte'),
('Manon', 'Martinez', '56 Rue de Provence', 'Virement'),
('Lucas', 'Chauvet', '89 Avenue de l Opera', 'Paypal'),
('Lea', 'Fontaine', '3 Boulevard Voltaire', 'Carte'),
('Nathan', 'Henry', '67 Rue des Pyrenees', 'Virement'),
('Sarah', 'Rousseau', '45 Rue de Belleville', 'Paypal'),
('Axel', 'Morel', '13 Rue des Martyrs', 'Carte'),
('Eva', 'Germain', '28 Rue Lafayette', 'Virement'),
('Leo', 'Faure', '31 Avenue de la Motte', 'Paypal'),
('Chloe', 'Renaud', '2 Rue de Passy', 'Carte'),
('Maxime', 'Barbier', '46 Rue Saint Lazare', 'Virement'),
('Nina', 'Picard', '14 Avenue de Clichy', 'Carte'),
('Yanis', 'Michel', '91 Rue de la Paix', 'Paypal'),
('Lola', 'Roy', '23 Rue des Arts', 'Virement'),
('Arthur', 'Caron', '58 Rue de Vaugirard', 'Carte'),
('Anais', 'Roux', '82 Rue Saint Antoine', 'Paypal'),
('Adrien', 'Benoit', '90 Rue du Bac', 'Virement'),
('Lina', 'Perrot', '77 Rue de Charenton', 'Carte'),
('Martin', 'Clement', '5 Boulevard Saint Michel', 'Paypal'),
('Melanie', 'Gilbert', '35 Rue de Sevres', 'Carte'),
('Adam', 'Gauthier', '88 Avenue Victor Hugo', 'Virement'),
('Isabelle', 'Renard', '20 Rue d Amsterdam', 'Paypal'),
('Simon', 'Lemoine', '44 Rue de l Universite', 'Carte'),
('Baptiste', 'Dufour', '62 Rue des Archives', 'Virement'),
('Louise', 'Bonnet', '91 Avenue de la Republique', 'Paypal'),
('Clement', 'Masson', '6 Rue de la Boetie', 'Carte'),
('Maelle', 'Schmitt', '53 Avenue des Champs Elysees', 'Virement'),
('Julien', 'Legros', '37 Rue Saint Denis', 'Paypal'),
('Ines', 'Marchand', '19 Rue du Louvre', 'Carte'),
('Lucas', 'Vidal', '29 Rue du Commerce', 'Virement'),
('Elena', 'Da Silva', '84 Rue des Abbesses', 'Paypal'),
('Bastien', 'Nguyen', '66 Rue Saint Sulpice', 'Carte'),
('Jade', 'Olivier', '72 Boulevard Haussmann', 'Virement'),
('Amandine', 'Leroy', '1 Rue de Rome', 'Carte'),
('Quentin', 'Fischer', '14 Boulevard de Strasbourg', 'Paypal'),
('Noah', 'Peters', '32 Rue de Lille', 'Virement'),
('Victoria', 'Weber', '89 Avenue des Ternes', 'Carte'),
('Lucas', 'Lambert', '120 Boulevard Saint Germain', 'Paypal'),
('Lise', 'Morel', '15 Avenue de la Porte', 'Virement'),
('Arnaud', 'Giraud', '20 Rue Victor Hugo', 'Carte'),
('Sabrina', 'Roche', '43 Rue de Rennes', 'Paypal'),
('Guillaume', 'Renard', '54 Rue Jouffroy', 'Virement'),
('Yasmine', 'Bouvier', '102 Avenue de Choisy', 'Carte'),
('Samuel', 'Bailly', '12 Rue Monge', 'Paypal'),
('Eva', 'Pascal', '17 Rue Buffon', 'Virement'),
('Mathieu', 'Morin', '89 Boulevard Arago', 'Carte'),
('Claire', 'David', '24 Rue Claude Bernard', 'Paypal'),
('Olivier', 'Brun', '56 Rue de l Abbe', 'Virement'),
('Sophie', 'Dupuy', '90 Rue Diderot', 'Carte'),
('Thomas', 'Carpentier', '47 Rue Daguerre', 'Paypal'),
('Nicolas', 'Delorme', '8 Rue des Rosiers', 'Virement'),
('Elodie', 'Faivre', '67 Rue de Flandres', 'Carte'),
('Hugo', 'Langlois', '14 Avenue Jean Jaures', 'Paypal'),
('Anais', 'Delaunay', '102 Rue du Faubourg', 'Virement'),
('Victor', 'Chartier', '77 Boulevard Haussmann', 'Carte'),
('Camille', 'Parent', '50 Avenue de la Grande Armee', 'Paypal'),
('Adrien', 'Leblanc', '33 Boulevard de Magenta', 'Virement'),
('Jules', 'Philippe', '11 Rue de Sevigne', 'Carte'),
('Charlotte', 'Guillot', '9 Rue Beauregard', 'Paypal'),
('Florent', 'Roy', '78 Rue des Batignolles', 'Virement'),
('Estelle', 'Berger', '22 Rue de Clignancourt', 'Carte'),
('Manon', 'Fleury', '45 Avenue de Saint Ouen', 'Paypal'),
('Antoine', 'Fabre', '91 Boulevard de Belleville', 'Virement'),
('Lucie', 'Roussel', '88 Avenue du Maine', 'Carte'),
('Bastien', 'Schneider', '62 Boulevard de la Villette', 'Paypal'),
('Laurent', 'Lemoine', '33 Rue Oberkampf', 'Virement'),
('Aurelie', 'Georges', '19 Rue de la Roquette', 'Carte'),
('Hector', 'Charlier', '25 Boulevard de Montparnasse', 'Paypal'),
('Eloise', 'Lemoine', '40 Avenue Parmentier', 'Virement'),
('Sylvain', 'Bourdon', '31 Rue de Belleville', 'Carte'),
('Morgane', 'Giraud', '73 Rue Saint Denis', 'Paypal'),
('Benjamin', 'Barre', '81 Boulevard Malesherbes', 'Virement'),
('Louise', 'Valette', '20 Avenue Ledru Rollin', 'Carte'),
('Mathilde', 'Maillard', '90 Boulevard Diderot', 'Paypal'),
('Martin', 'Blanchet', '68 Rue Saint Antoine', 'Virement'),
('Claire', 'Legendre', '11 Rue de la Folie Mericourt', 'Carte'),
('Lilian', 'Dumont', '13 Boulevard de Clichy', 'Paypal'),
('Simon', 'Lebrun', '19 Rue de Reuilly', 'Virement'),
('Jade', 'Meunier', '55 Rue des Archives', 'Carte'),
('Gabriel', 'Clerc', '24 Avenue de la Republique', 'Paypal'),
('Lola', 'Prevost', '60 Rue du Mont Cenis', 'Virement'),
('Florian','Dagnas', '20 Bd Général de Gaulle', 'Paypal'),
('Edgar','Dutrottoir', '20 Bd Général de Gaulle', 'Virement'),
('Jeremy','pissenlit', '30 rue des petits cochons', 'Paypal'),
('Rémy','pissenlit', '20 Bd Général de Gaulle', 'Paypal');