CREATE TABLE employes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(50),
    prenom VARCHAR(50),
    adresse VARCHAR(100),
    anciennete INT,
    metier VARCHAR(50)
);

INSERT INTO employes (nom, prenom, adresse, anciennete, metier) VALUES
('Dupont', 'Jean', '10 Rue de Paris, Paris', 5, 'Directeur General'),
('Martin', 'Sophie', '15 Avenue des Champs, Lyon', 3, 'Responsable Marketing'),
('Durand', 'Paul', '25 Boulevard Saint Germain, Marseille', 8, 'Chef de Produit'),
('Leroy', 'Lucie', '30 Rue de la Republique, Lille', 10, 'Responsable des Ventes'),
('Moreau', 'Marc', '1 Place de la Concorde, Nantes', 2, 'Gestionnaire de Franchise'),
('Simon', 'Claire', '20 Rue de la Liberte, Nice', 1, 'Responsable des Ressources Humaines'),
('Benoit', 'Julien', '14 Avenue Victor Hugo, Bordeaux', 12, 'Chef de Cuisine'),
('Gauthier', 'Alice', '5 Quai de la Loire, Strasbourg', 4, 'Responsable Qualite'),
('Garnier', 'Nicolas', '12 Rue des Fleurs, Toulouse', 6, 'Manager de Restaurant'),
('Roux', 'Elodie', '22 Boulevard des Martyrs, Montpellier', 2, 'Caissier'),
('Noel', 'Thomas', '17 Rue du Loup, Grenoble', 3, 'Cuisinier'),
('Pires', 'Emilie', '8 Rue du Moulin, Rennes', 7, 'Responsable Logistique'),
('Chevalier', 'Francois', '14 Avenue de la Gare, Dijon', 5, 'Analyste Financier'),
('Leblanc', 'Celine', '25 Rue de la Mer, Caen', 3, 'Responsable IT'),
('Marechal', 'Antoine', '5 Rue des Ecoles, Saint Etienne', 11, 'Responsable de la Communication'),
('Boucher', 'Sabrina', '18 Rue de lHorloge, Amiens', 2, 'Formateur'),
('Barbier', 'Victor', '28 Rue des Grands Champs, Reims', 9, 'Charge de la Sécurite'),
('Langlois', 'Camille', '30 Rue des Erables, Toulon', 4, 'Community Manager'),
('David', 'Laure', '15 Rue des Peupliers, Clermont Ferrand', 6, 'Responsable de lInnovation'),
('Martinez', 'Eric', '22 Boulevard de la Paix, Angers', 7, 'Analyste de Marche'),
('Bernard', 'Juliette', '21 Rue de lEcole, Paris', 4, 'Directeur General'),
('Collet', 'Nicolas', '14 Avenue de la Liberté, Lyon', 3, 'Responsable Marketing'),
('Garnier', 'Fanny', '30 Boulevard des Arts, Marseille', 6, 'Chef de Produit'),
('Peyton', 'Alex', '15 Rue de lInspiration, Lille', 9, 'Responsable des Ventes'),
('Riviere', 'Thomas', '4 Place du Souvenir, Nantes', 1, 'Gestionnaire de Franchise'),
('Boucher', 'Marc', '22 Rue de la Paix, Nice', 2, 'Responsable des Ressources Humaines'),
('Gaucher', 'Cecile', '17 Avenue des Champs, Bordeaux', 11, 'Chef de Cuisine'),
('Nivet', 'Estelle', '11 Rue des Fleurs, Strasbourg', 5, 'Responsable Qualite'),
('Bourgeois', 'Simon', '30 Boulevard du Jardin, Toulouse', 7, 'Manager de Restaurant'),
('Lemoine', 'Luc', '10 Rue des Lilas, Montpellier', 2, 'Caissier'),
('Leroux', 'Elise', '25 Rue de la Source, Grenoble', 3, 'Cuisinier'),
('Deschamps', 'Victor', '20 Rue des Vignes, Rennes', 8, 'Responsable Logistique'),
('Morin', 'Gabriel', '5 Rue de la Mer, Dijon', 5, 'Analyste Financier'),
('Dufour', 'Chloe', '29 Boulevard de la Liberté, Caen', 6, 'Responsable IT'),
('Brun', 'Antoine', '14 Rue du Commerce, Saint Etienne', 2, 'Responsable de la Communication'),
('Besson', 'Olivier', '17 Rue de la Montagne, Amiens', 7, 'Formateur'),
('Marchand', 'Sophie', '30 Rue des Chênes, Reims', 3, 'Charge de la Sécurite'),
('Jourdain', 'Nina', '15 Rue des Hirondelles, Toulon', 4, 'Community Manager'),
('Pichon', 'Eric', '12 Rue des Cerisiers, Clermont Ferrand', 9, 'Responsable de lInnovation'),
('Gaillard', 'Alice', '20 Avenue du Lac, Angers', 6, 'Analyste de Marche'),
('Charpentier', 'Léo', '8 Rue de la Foret, Tours', 3, 'Directeur General'),
('Fabre', 'Charlotte', '15 Rue des Capucins, Marseille', 5, 'Responsable Marketing'),
('Lacombe', 'Julien', '27 Rue de la Mer, Lyon', 6, 'Chef de Produit'),
('Barre', 'Marie', '30 Boulevard du Parc, Lille', 7, 'Responsable des Ventes'),
('Giraud', 'Hugo', '22 Rue des Forges, Nantes', 1, 'Gestionnaire de Franchise'),
('Vasseur', 'Ines', '18 Avenue de la Lumière, Nice', 4, 'Responsable des Ressources Humaines'),
('Gillet', 'Arthur', '11 Rue de la Joie, Bordeaux', 12, 'Chef de Cuisine'),
('Delaunay', 'Sonia', '5 Quai des Rêves, Strasbourg', 3, 'Responsable Qualite'),
('Legendre', 'Noah', '12 Rue des Rosiers, Toulouse', 5, 'Manager de Restaurant'),
('Lefevre', 'Samantha', '25 Boulevard des Acacias, Montpellier', 2, 'Caissier'),
('Desrosiers', 'Raphael', '20 Rue de lAmitié, Grenoble', 3, 'Cuisinier'),
('Gaultier', 'Clara', '9 Rue du Bonheur, Rennes', 8, 'Responsable Logistique'),
('Allard', 'Julien', '17 Avenue des Cèdres, Dijon', 5, 'Analyste Financier'),
('Vallet', 'Nadia', '30 Rue des Lilas, Caen', 3, 'Responsable IT'),
('Martel', 'Elisa', '15 Rue de la Nouvelle, Saint Etienne', 4, 'Responsable de la Communication'),
('Renaud', 'Victor', '22 Rue des Cœurs, Amiens', 2, 'Formateur'),
('Bernard', 'Lucie', '1 Rue des Voyageurs, Reims', 7, 'Charge de la Sécurite'),
('Lamy', 'Antoine', '14 Rue de la Nature, Toulon', 6, 'Community Manager'),
('Blanc', 'Adele', '29 Rue de la Roseraie, Clermont Ferrand', 4, 'Responsable de lInnovation'),
('Lopez', 'Elise', '5 Boulevard de lHorizon, Angers', 8, 'Analyste de Marche'),
('Dufresne', 'Gabriel', '14 Rue de la Plage, Marseille', 7, 'Directeur General'),
('Caron', 'Chloe', '20 Boulevard de la Lune, Lyon', 5, 'Responsable Marketing'),
('Guillot', 'Lucas', '1 Rue de lEspace, Lille', 6, 'Chef de Produit'),
('Pichon', 'Camille', '9 Rue de la Terre, Nantes', 3, 'Responsable des Ventes'),
('Marchal', 'Anais', '15 Rue du Ciel, Nice', 2, 'Gestionnaire de Franchise'),
('Bourdon', 'Maxime', '30 Rue des Nuages, Bordeaux', 4, 'Responsable des Ressources Humaines'),
('Pereira', 'Alice', '17 Rue de la Mer, Strasbourg', 8, 'Chef de Cuisine'),
('Delaunay', 'Lena', '22 Rue de la Vallée, Toulouse', 3, 'Responsable Qualite'),
('Rousseau', 'Thibault', '5 Rue des Champs, Montpellier', 5, 'Manager de Restaurant'),
('Marchand', 'Sophie', '18 Rue des Pins, Grenoble', 2, 'Caissier'),
('Leroy', 'Clement', '7 Rue de la Nature, Rennes', 4, 'Cuisinier'),
('Bourgeois', 'Juliette', '12 Rue des Fleurs, Dijon', 6, 'Responsable Logistique'),
('Gonzalez', 'Theo', '30 Boulevard des Étoiles, Caen', 5, 'Analyste Financier'),
('Brunet', 'Lise', '11 Rue des Merveilles, Saint Etienne', 7, 'Responsable IT'),
('Chevalier', 'Hugo', '19 Rue des Rencontres, Amiens', 3, 'Responsable de la Communication');
