CREATE TABLE USER (
    UserId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    FirstName VARCHAR(80) NOT NULL,
    LastName VARCHAR(80) NOT NULL,
    Addrese VARCHAR(80) NOT NULL,
    FavoritePayment VARCHAR(10) NOT NULL,
    PaymentHistoryId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    InvoicesId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);